services:
  django_app:
    build: .
    image: family-tree
    container_name: family-tree
    network_mode: bridge
    environment:
      DB_ENGINE: django.db.backends.postgresql
      PGDATABASE: ${PGDATABASE}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}
      DEBUG: "False"
      ALLOWED_HOSTS: "*"
    volumes:
      - django_static:/app/static
      - django_media:/app/media
    restart: always

volumes:
  django_static:
  django_media:
